site_name: Python covid-19  Documentation
site_description: "A client to get data from covid-19"
site_author: "Davi Wesley"
repo_url: "https://github.com/daviwesley/python-covid"
pages:
  - Home: index.md
theme:
  name: "material"
  language: "en"
  palette:
    primary: "green"
    accent: "green"

extra:
  search:
    language: "en, pt"

markdown_extensions:
  - admonition
